version: '2'
services:
  postgres_ser:
    image: postgres:9.6.2-alpine
    volumes:
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
      POSTGRES_DB: logindb
    ports:
      - "15432:5432"

  web:
    image: nodejs-login-app:latest
    build: .
    #command: npm run dev
    ports:
      - "3006:4000"
    depends_on:
      - postgres_ser
    environment:
      DB_HOST: postgres_ser
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
      POSTGRES_DB: logindb

